branchProtectionRules:
  - pattern: master
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - lint
      - test (14)
      - test (16)
      - test (18)
      - cla/google
      - windows
      - OwlBot Post Processor
