branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: true
    requiredStatusCheckContexts:
      - lint
      - test (14)
      - test (16)
      - test (18)
      - cla/google
      - windows
      - OwlBot Post Processor
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: jsteam-admins
    permission: admin
  - team: jsteam
    permission: push
