container:
  image: node:12

lint_task:
  install_script: npm ci
  test_script: npm run lint

test_task:
  container:
    matrix:
      image: node:13
      image: node:12
      image: node:10
      image: node:8
  install_script: npm ci
  test_script: npm test

coverage_task:
  script:
    - npm ci
    - npm test
    - npm run codecov

publish_task:
  only_if: $CIRRUS_TAG =~ '^v.*'
  depends_on:
    - test
    - lint
  environment:
    NPM_TOKEN: ENCRYPTED[188593d2219e49e28e05c983a768a7e89ef89441f07f450a58744161674b2e7f127caff0a8021bb5bb75a09d4e18750f]
  script:
    - npm ci
    - npm run compile
    - echo "//wombat-dressing-room.appspot.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --registry https://wombat-dressing-room.appspot.com/
