---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/

unit_tests: &unit_tests
  steps:
    - checkout
    - run: npm ci
    - run: npm test

version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node8:
          filters: *release_tags
      - node10:
          filters: *release_tags
      - node11:
          filters: *release_tags
      - node12:
          filters: *release_tags
      - lint:
          filters: *release_tags
      - codecov:
          filters: *release_tags
      - publish_npm:
          requires:
            - node8
            - node10
            - node11
            - node12
          filters:
            branches:
              ignore: /.*/
            <<: *release_tags

jobs:
  node8:
    docker:
      - image: node:8
        user: node
    <<: *unit_tests
  node10:
    docker:
      - image: node:10
        user: node
    <<: *unit_tests
  node11:
    docker:
      - image: node:11
        user: node
    <<: *unit_tests
  node12:
    docker:
      - image: node:12
        user: node
    <<: *unit_tests
  codecov:
    docker:
      - image: node:12
        user: node
    steps:
      - checkout
      - run: npm ci
      - run: npm test
      - run: npm run codecov
  lint:
    docker:
      - image: node:12
        user: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  publish_npm:
    docker:
      - image: node:10
        user: node
    steps:
      - checkout
      - run: npm ci
      - run: echo "//wombat-dressing-room.appspot.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish --registry https://wombat-dressing-room.appspot.com/
